export const GET_POST_LIKES = 'GET_POST_LIKES';
export const GET_COMMENT_LIKES = 'GET_COMMENT_LIKES';
export const CREATE_POST_LIKE = 'CREATE_POST_LIKE';
export const CREATE_COMMENT_LIKE = 'CREATE_COMMENT_LIKE';
export const DELETE_POST_LIKE = 'DELETE_POST_LIKE';
export const DELETE_COMMENT_LIKE = 'DELETE_COMMENT_LIKE';
export const LIKES_ERROR = 'LIKES_ERROR';
